<template>
  <div>
    <v-toolbar
      color="transparent"
    >
      <v-toolbar-side-icon></v-toolbar-side-icon>
      <v-toolbar-title>Setting</v-toolbar-title>
    </v-toolbar>
  </div>
</template>
